# Generated by Django 5.2.17 on 2026-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
